version: '3.8'

services:
  wordpress:
    image: wordpress:6.4-php8.1-apache
    container_name: sparkpress_web
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
      - ./src/themes/sparkpress:/var/www/html/wp-content/themes/sparkpress
      - ./src/plugins/sparkpress:/var/www/html/wp-content/plugins/sparkpress
  db:
    image: mysql:8.1
    container_name: sparkpress_db
    restart: always
    env_file:
      - .env
    volumes:
    - db:/var/lib/mysql
volumes:
  wordpress:
  db:
